### PR TITLE
Create MQTT subtopic to be inline with industry best practices

### PR DESCRIPTION
**Pull request by kidmock**
MQTT Best Practices suggest that each device should be it's own subtopic.

Additionally, the Tiltpi JSON uses different attribute names and I think the should be the same for consistency

### CODE REVIEW

**Comment by thorrak** [comment]
Admittedly, I'm not that familiar with homeassistant and MQTT. Is there any reason someone who doesn't use home assistant but does want MQTT wouldn't want the two additional subtopics?

If yes, we can add a tick box for home assistant support. If you can't think of one (ie - its just additional data that most endpoints could ignore) then I'd just assume do without one.

**Comment by pletch** [comment]
I chatted with kidmock about this exact topic.  There really doesn't seem to be any drawback to having the home assistant config topics be emitted.  If there are no subscribers, the messages are simply ignored.

**Comment by thorrak** [comment]
That works for me!

**Comment by kidmock** [comment]
I think we are done messing around with this fork. Everything is sanitized, standardized, and finalized for beautifully working MQTT support and configuration topics for home-assistant.io auto discovery.

I highly recommend looking into MQTT as it might be a great fit for controlling fermentation in the core of fermentrack. MQTT has  become the de-facto standard for sensor data and event triggers in the IoT world.

**Comment by thorrak** [comment]
Thanks again for sending this through - for now I'm merging this to a new branch for now as I work towards the next release.

I'll try to get this all packaged up and pushed out ASAP.

**Pull request merged**
