### PR TITLE
Update Github Actions to automatically manage releases

### PR DESCRIPTION
**Pull request by TaplistIOTeam**
This change will:

* Create (or update) a tag and release named `latest-{master,devel}` every time a PR is merged to one of those branches; and
* Create a new release when a tag matching `v*` is pushed

The former means "bleeding edge" auto-built binaries should always be available, e.g. to interested testers. The latter I hope removes a chore associated with cutting new releases: just push the tag & let the action handle the rest.

Because of the conditional nature of those triggers, we won't be able to observe either of these things in this PR, unless it is merged. So I did a fake PR & merge in our fork: here's [the PR](https://github.com/TaplistIO/tiltbridge/pull/4), [the action that ran once merged](https://github.com/TaplistIO/tiltbridge/actions/runs/754013413), and [the `latest-devel` release the action created](https://github.com/TaplistIO/tiltbridge/releases/tag/latest-devel).

### CODE REVIEW

**Review by thorrak — APPROVED** [review]

**Comment by thorrak** [comment]
Ugh. You're going to make me build actual Github integration for TiltBridge's firmware list, aren't you?

😢

**Comment by mik3y** [comment]
Hahah. That thought did cross my mind! Hit up releases api client side from the firmware page... :)

**Comment by TaplistIOTeam** [comment]
Hahah. That thought did cross my mind! Hit up releases api client side from the firmware page... :)

**Comment by thorrak** [comment]
> Hahah. That thought did cross my mind! Hit up releases api client side from the firmware page... :)

Interestingly enough, my project earlier today was building basically this exact code for a different project. I will admit I was thinking of going down this route... 

Project for later this year. ;)

**Comment by thorrak** [comment]
BTW - I'm holding off on merging this until probably ~Sunday due to the way that BrewFlasher integrates with everything. Although I don't expect that this will cause any issues, I also don't want to get excited about having automatically updating releases and stay up late working on the same.

**Comment by TaplistIOTeam** [comment]
Haha, no problem! Run with it however + whenever you see fit; whipped up out of pure curiosity.

**Comment by TaplistIOTeam** [comment]
@lbussy I notice you are still maintaining firmware manually in the cloud branch. If you're interested, you could merge this and start getting some mileage on it. Something like the following:

* Merge this PR as is. (No releases get auto-created until a tag is pushed).
* Within the `cloud` branch, or wherever active development is happening, start using tags to trigger builds. eg:
    * `v2.0.0-cloud-pre1`

No rush, just a small idea to start getting some cycles + keep this from bit rotting.

**Comment by thorrak** [comment]
Man, I have the memory of a goldfish. Merging.

**Pull request merged**
