### PR TITLE
Add note on 404 error

### PR DESCRIPTION
**Pull request by nightcrawler91**
I first saw this as an error in the Tiltbridge itself, it wasn't until later that I noticed that it was just part of the initial setup.

### CODE REVIEW

**Comment by thorrak** [comment]
Hey there - and thanks for the PR!

Just to understand what you were seeing, when you attempted to navigate to the URL of your TiltBridge, did you get a 404 error just initially (like - it flashed a 404 and then navigated to the TiltBridge after a half-second or so) or did you experience something else?

**Comment by nightcrawler91** [comment]
> Hey there - and thanks for the PR!
> 
> Just to understand what you were seeing, when you attempted to navigate to the URL of your TiltBridge, did you get a 404 error just initially (like - it flashed a 404 and then navigated to the TiltBridge after a half-second or so) or did you experience something else?
> 

The portal was actually loading fine, but in the home page on the area where the current results being read by the tilt are displayed, before I configured it to work (I'm using Brewfather) I saw this: https://photos.app.goo.gl/UstNBgCSmNHxwigo8 (I even took a picture to ask a friend if I had somehow screwed things up). Later once I had configured everything, this changed to show my tilt readings, so I am thinking that this is mostly the home page trying to load data from a source that has not been configured yet.

**Comment by thorrak** [comment]
Huh. That's odd. You didn't happen to grab a screenshot including the full URL you were trying to access, did you?

I actually think there may be a bug here that needs to be squished.

**Comment by nightcrawler91** [comment]
Sorry :( I just quickly took this with my phone to troubleshoot with my friend and because it fixed itself later I didn't think much of it. I thought this was just a part of the initial setup and that's why I issued a PR to update the docs just because I thought others could also get confused.

**Comment by thorrak** [comment]
All good! Now that I know there's a potential issue, I can try to track it down!

Thank you!

**Comment by thorrak** [comment]
I poked through the code a bit, and unfortunately nothing obvious is jumping out. Just to be sure I understand the chain of events, is the following what happened:

1. You built/flashed the TiltBridge
2. You plugged it in, and it spun up the configuration AP
3. You connected to the configuration AP and set the TiltBridge to connect to your WiFi network
4. The TiltBridge restarted, connected to your WiFi, and you reconnected your device to your WiFi network as well
5. You attempted to access `http://tiltbridge.local/` and got the 404 page you posted a screenshot of

**Comment by nightcrawler91** [comment]
Just like that!

**Comment by thorrak** [comment]
Unfortunately, I can't replicate this issue on my end. :(

I've tried reinstalling/reconfiguring my TiltBridge, and things seem to be working as expected. The only thing I can think is that something was already in your URL when you attempted to access the page - potentially something left over from a previous configuration attempt. It doesn't make much sense, but that's my best guess at the moment.

I'll keep this in mind and will try to debug further if I encounter it in the future. For now though, I'm going to close this PR.

**Pull request closed without merging**
