### PR TITLE
Add board support for M5Stack M5Stick-C; add "no LCD" support

### PR DESCRIPTION
**Pull request by TaplistIOTeam**
Per discussion, it may actually be quite feasible to get the display working on this device. I gave it a shot and didn't get it to work; figure checkpoint this here & continue tinkering.

### CODE REVIEW

**Comment by lbussy** [comment]
As I said on HBT, I have an M5 sitting here.  As John will tell you, I can't not eff with a problem so I'll have a look tomorrow.

**Comment by TaplistIOSupport** [comment]
Ah! I used the PlatformIO command line tools:

```
$ pio run -e m5stickc --target upload
```

I _believe_ how this works is it strobes the usb serial port's `RST` line, but don't quote me on that.

**Comment by lbussy** [comment]
Yeah, that's how it's supposed to work.  For whatever reason, it's not working with the stick.  All it does is reset the device over and over but never quite "catches" the bootloader.

I'm using PIO as well.  I guess I'll have to find my star-point bits, tear this apart, and see if I can do a button dance.

**Comment by TaplistIOTeam** [comment]
Hmm yeah, I'm new to this device, wish I had more tricks up my sleeve. (To be honest I was a bit surprised I was able to get it all working as quickly as I did!)

**Comment by TaplistIOTeam** [comment]
Okay, a tiny bit of digging suggests some possible workarounds, rootcaused in the usb-serial device:

* Try shorting `G0` to `GND`: Here's a [forum thread I found](https://community.m5stack.com/topic/1369/m5stickc-usb-driver-and-catalina/20) which suggests that.
* [This issue](https://github.com/espressif/esptool/issues/502) suggests [updating the usb-serial chip's firmware](https://community.m5stack.com/topic/1591/m5stickc-atom-on-macos-catalina-can-t-upload-esp32-timed-out-waiting-for-packet-header-solution-solved) can also resolve the issue.

**Comment by lbussy** [comment]
I did the G0 to GND dance, I can see it's entered bootloader mode but it will still not flash, strangely.  The driver mentioned is for MacOS only and I am on Windows.

I'll get back to it later today maybe and see what I can do.

**Comment by lbussy** [comment]
Okay, setting RTS and DTR manually, grounding G0, and a small animal sacrifice all worked.  Now I can test.

**Comment by TaplistIOTeam** [comment]
Rad! I hope the animal wasn't very cute. Cheers!

**Comment by lbussy** [comment]
First blush:  I HATE this damned board!  There does not seem to be the same support for a reset initiated from the serial connection, so the jumper wire is required every time I want to flash.  I have it running, however, mDNS is not responding at the moment.  Other than that it *seems* to work.

More poking is necessary.

**Comment by TaplistIOTeam** [comment]
> I have it running, however, mDNS is not responding at the moment. Other than that it seems to work.

Hmm! Wonder what that could be. Mine responded to mDNS without any additional coaxing.

**Comment by lbussy** [comment]
There's exactly no telling.  The good news is, I seem to break things pretty well so as a tester I'm golden.

**Pull request merged**
